# Generated by Django 4.0.4 on 2022-05-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_maintenance_options_alter_plant_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='Watering Frequency',
            field=models.IntegerField(choices=[(1, 'Daily'), (3, 'Biweekly'), (7, 'Weekly'), (14, 'Two Weeks'), (21, 'Three Weeks'), (30, 'Monthly')], default=7),
        ),
    ]
