# Generated by Django 4.0.4 on 2022-05-30 00:30

from django.db import migrations, models
import main_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_rename_watering frequency_plant_watering_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(validators=[main_app.models.validate_date]),
        ),
    ]
